# Generated by Django 2.2.16 on 2022-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221029_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='reviews.Genre', verbose_name='Произведение'),
        ),
    ]
