# Generated by Django 2.2.28 on 2022-10-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221029_2043'),
        ('reviews', '0007_auto_20221030_1914'),
    ]

    operations = [
    ]
