# Generated by Django 2.2.16 on 2022-10-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20221030_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Рейтинг', null=True),
        ),
    ]
