# Generated by Django 2.2.16 on 2022-10-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
